/* Demo / yedek içerik — backend yokken ya da soğuk başlangıçta gösterilir.
   Saf veri; backend çeviri hattının üreteceği JSON'un simülasyonudur. */

export const MOCK_ARTICLES = [
  {
    id: "iklim-zirvesi",
    lead: true,
    category: "Dünya",
    kicker: "İklim Diplomasisi",
    title:
      "İklim Zirvesinde Tarihi Uzlaşı: Fosil Yakıtlardan Kademeli Çıkış Metne Girdi",
    dek: "Maraton müzakerelerin ardından kabul edilen taslak, bağlayıcı yaptırım içermese de küresel enerji geçişine ilk kez ortak bir yön çiziyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "Cenevre",
    date: "25 Haziran 2026",
    readTime: "7 dk okuma",
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1400&q=80",
    imageCaption:
      "Zirvenin kapanışında kabul edilen metin, fosil yakıtlardan çıkış ifadesini ilk kez resmî sonuç belgesine taşıdı.",
    imageCredit: "Fotoğraf: Reuters",
    source: { name: "Reuters", url: "https://www.reuters.com" },
    body: [
      "Yüzü aşkın ülkenin katıldığı iklim zirvesi, fosil yakıtlardan kademeli çıkışı ilk kez resmî sonuç metnine taşıyan bir uzlaşıyla sona erdi. Karar, ihlal hâlinde işletilecek bağlayıcı bir yaptırım mekanizması içermiyor; ancak müzakereciler, ifadenin küresel enerji politikaları açısından uzun süredir aşılamayan bir eşiği geçtiğini belirtiyor.",
      "Metnin son hâli, petrol ihraç eden ülkeler ile iklim finansmanı talep eden gelişmekte olan ekonomiler arasındaki gerilimin damga vurduğu uzun bir pazarlığın ürünü oldu. Taraflar, geçiş sürecinin maliyetinin nasıl paylaşılacağı konusunda yalnızca genel bir çerçevede anlaşabildi.",
      "Çevre örgütleri sonucu temkinli karşıladı. Birçok kuruluş, metnin yönünü doğru bulmakla birlikte, somut takvim ve denetim eksikliğinin hedefleri zayıflattığı uyarısında bulundu.",
      "Sıradaki aşama, ülkelerin bu çerçeveyi kendi ulusal taahhütlerine yansıtması olacak. Gözler, bir sonraki zirveye kadar açıklanacak güncellenmiş emisyon planlarına çevrildi.",
    ],
  },
  {
    id: "kentsel-donusum",
    category: "Türkiye",
    kicker: "Kentsel Politika",
    title:
      "Kentsel Dönüşümde Yeni Yönetmelik: Riskli Yapılar İçin Süreç Yeniden Düzenlendi",
    dek: "Düzenleme, deprem riski taşıyan binalarda dönüşümü hızlandırmayı ve hak sahiplerinin mali yükünü azaltmayı hedefliyor.",
    originalTitle:
      "SON DAKİKA: Milyonları ilgilendiren O KARAR çıktı! Evinizi kaybetmemek için yapmanız gereken tek şey...",
    author: "Yeniden Yazım: Singularity AI Bot",
    rewritten: true,
    desk: "Ankara",
    date: "25 Haziran 2026",
    readTime: "5 dk okuma",
    image:
      "https://images.unsplash.com/photo-1486325212027-8081e485255e?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Yeni yönetmelik, riskli yapı tespitinden yıkım ve yeniden inşa aşamasına kadar olan süreci kısaltmayı amaçlıyor.",
    imageCredit: "Fotoğraf: NTV",
    source: { name: "NTV", url: "https://www.ntv.com.tr" },
    body: [
      "Riskli yapıların dönüşümüne ilişkin yönetmelik, başvuru ve tespit süreçlerini yeniden düzenleyen değişikliklerle güncellendi. Düzenlemenin temel amacı, deprem riski taşıyan binalarda dönüşümü hızlandırmak ve hak sahiplerinin karşılaştığı bürokratik ve mali engelleri azaltmak olarak açıklandı.",
      "Yeni çerçeveye göre risk tespiti, yıkım kararı ve yeniden inşa izinleri için öngörülen idari süreler kısaltılıyor; hak sahiplerine sağlanan kira ve taşınma desteklerinin kapsamı ise yeniden tanımlanıyor.",
      "Şehir plancıları ve mühendislik örgütleri, hız kazandıran adımları olumlu bulmakla birlikte, denetimin niteliğinden ödün verilmemesi gerektiğini vurguluyor. Uzmanlara göre sürecin başarısı, sahadaki uygulamanın titizliğine bağlı olacak.",
      "Düzenlemenin kademeli olarak yürürlüğe gireceği, önceliğin yüksek riskli bölgelerdeki yapı stokuna verileceği belirtildi.",
    ],
  },
  {
    id: "piyasa-faiz",
    category: "Ekonomi",
    kicker: "Para Politikası",
    title: "Küresel Piyasalar Merkez Bankalarının Faiz Sinyaline Kilitlendi",
    dek: "Yatırımcılar, enflasyondaki yavaşlamanın faiz indirimi beklentilerini güçlendirip güçlendirmeyeceğini değerlendiriyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "New York",
    date: "24 Haziran 2026",
    readTime: "6 dk okuma",
    image:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Tahvil getirileri ve hisse endeksleri, merkez bankalarının atacağı bir sonraki adıma göre yön arıyor.",
    imageCredit: "Fotoğraf: Bloomberg",
    source: { name: "Bloomberg", url: "https://www.bloomberg.com" },
    body: [
      "Küresel piyasalar, başlıca merkez bankalarının faiz patikasına ilişkin vereceği sinyalleri beklerken temkinli bir seyir izliyor. Yatırımcıların odağında, son verilerde gözlenen enflasyon yavaşlamasının para politikasında gevşemeye kapı aralayıp aralamayacağı sorusu var.",
      "Analistler, enflasyondaki düşüşün istikrarlı hâle gelmesi durumunda faiz indirimi beklentilerinin güçleneceğini; ancak bankaların erken bir gevşemeden kaçınmak için ihtiyatlı bir dil tutmayı sürdürebileceğini belirtiyor.",
      "Tahvil getirilerindeki hareketlilik, hisse senedi piyasalarındaki sektörel ayrışmayı da derinleştiriyor. Faize duyarlı teknoloji hisseleri öne çıkarken, savunmacı sektörler görece yatay seyrediyor.",
      "Piyasa katılımcıları, önümüzdeki dönemde açıklanacak istihdam ve büyüme verilerinin, fiyatlamaların yönünü belirleyen asıl etken olacağı görüşünde.",
    ],
  },
  {
    id: "ai-cip-talebi",
    category: "Teknoloji",
    kicker: "Yapay Zeka Altyapısı",
    title:
      "Yapay Zeka Çip Talebi, Veri Merkezi Yatırımlarını Rekor Seviyeye Taşıdı",
    dek: "Bulut sağlayıcılarının kapasite yarışı, enerji ve tedarik zinciri üzerinde yeni baskılar oluşturuyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "San Francisco",
    date: "24 Haziran 2026",
    readTime: "6 dk okuma",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Büyük dil modellerinin (LLM) çıkarım (inference) yükü, hızlandırıcı çiplere olan talebi katladı.",
    imageCredit: "Fotoğraf: Reuters",
    source: { name: "Reuters", url: "https://www.reuters.com" },
    body: [
      "Yapay zeka hızlandırıcı çiplerine olan talep, bulut sağlayıcılarının veri merkezi yatırımlarını rekor seviyeye taşıdı. Büyük dil modellerinin (LLM) hem eğitim hem de çıkarım (inference) yükü, işlem kapasitesine yönelik talebi öngörülerin ötesine çıkardı.",
      "Sektör yöneticileri, asıl darboğazın yalnızca çip üretimi değil; bu çipleri besleyecek elektrik, soğutma ve yüksek bant genişlikli bellek (HBM) tedariki olduğunu vurguluyor. Kapasite yarışı, enerji altyapısı üzerinde de yeni baskılar oluşturuyor.",
      "Maliyet tarafında ise çelişkili bir tablo var: Birim çıkarım maliyeti düşmeyi sürdürürken, toplam talebin patlaması nedeniyle şirketlerin altyapı harcamaları artıyor. Analistler bunu “verimlilik arttıkça tüketimin de artması” olarak yorumluyor.",
      "Uzmanlara göre önümüzdeki dönemde rekabet, ham işlem gücünden çok enerji verimliliği ve tedarik zinciri dayanıklılığı üzerinden şekillenecek.",
    ],
  },
  {
    id: "anadolu-kazi",
    category: "Kültür Sanat",
    kicker: "Arkeoloji",
    title:
      "Anadolu'daki Kazılarda Antik Kente Ait Yeni Bir Bölüm Gün Yüzüne Çıktı",
    dek: "Arkeologlar, buluntuların bölgenin ticaret tarihine ilişkin bilinenleri genişletebileceğini belirtiyor.",
    originalTitle:
      "Kazıda bulunanlar HERKESİ ŞOKE ETTİ! Arkeologlar gözlerine inanamadı, bakın ne çıktı...",
    author: "Yeniden Yazım: Singularity AI Bot",
    rewritten: true,
    desk: "İzmir",
    date: "23 Haziran 2026",
    readTime: "4 dk okuma",
    image:
      "https://images.unsplash.com/photo-1599946347371-68eb71b16afc?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Kazı ekibi, açığa çıkarılan yapının kentin kamusal yaşamına ait olduğunu değerlendiriyor.",
    imageCredit: "Fotoğraf: BBC Türkçe",
    source: { name: "BBC Türkçe", url: "https://www.bbc.com/turkce" },
    body: [
      "Anadolu'da sürdürülen kazı çalışmalarında, antik bir kente ait olduğu değerlendirilen yeni bir yapı topluluğu gün yüzüne çıkarıldı. Arkeologlar, buluntuların bölgenin ticaret ve gündelik yaşam tarihine ilişkin bilinenleri genişletebileceğini belirtiyor.",
      "Kazı ekibinin ilk değerlendirmelerine göre, açığa çıkarılan bölüm kentin kamusal alanlarından birine ait olabilir. Yapıdaki düzen ve kullanılan malzeme, dönemin yerleşim anlayışına dair ipuçları sunuyor.",
      "Buluntuların ayrıntılı tarihlendirmesi ve niteliğinin belirlenmesi için laboratuvar analizlerinin süreceği; çalışmaların sonuçlarının akademik yayınlarla paylaşılacağı bildirildi.",
    ],
  },
  {
    id: "olimpiyat-hazirlik",
    category: "Spor",
    kicker: "Olimpiyatlar",
    title: "Olimpiyat Hazırlıkları Hız Kazandı; Sürdürülebilirlik Öne Çıkıyor",
    dek: "Organizasyon komitesi, tesislerin büyük bölümünün mevcut altyapıdan uyarlanacağını açıkladı.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "Paris",
    date: "23 Haziran 2026",
    readTime: "5 dk okuma",
    image:
      "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Komite, yeni inşaat yerine mevcut tesislerin yeniden işlevlendirilmesine öncelik verildiğini açıkladı.",
    imageCredit: "Fotoğraf: AP",
    source: { name: "AP", url: "https://apnews.com" },
    body: [
      "Olimpiyat oyunlarına yönelik hazırlıklar hız kazanırken, organizasyon komitesi bu kez merkeze sürdürülebilirliği koyduğunu açıkladı. Komiteye göre tesislerin büyük bölümü sıfırdan inşa edilmeyecek; mevcut altyapı yeniden işlevlendirilecek.",
      "Yaklaşımın temel gerekçesi olarak maliyetlerin kontrol altında tutulması ve oyunların uzun vadeli çevresel etkisinin azaltılması gösteriliyor. Geçici yapılar ve yenilenebilir enerji kullanımının kapsamının genişletilmesi planlanıyor.",
      "Ulaşım ve güvenlik planlaması ise hazırlıkların en kritik başlıkları arasında. Komite, kentteki günlük yaşamı en az düzeyde aksatacak bir lojistik modeli üzerinde çalışıldığını belirtti.",
      "Sporcu kotaları ve eleme takvimine ilişkin ayrıntıların önümüzdeki haftalarda netleşmesi bekleniyor.",
    ],
  },
  {
    id: "borsa-sirket",
    category: "İş",
    kicker: "Şirketler",
    title: "Teknoloji Şirketlerinden Yeni Yatırım Dalgası: İstihdam Hedefleri Büyüyor",
    dek: "Sektör temsilcileri, nitelikli iş gücü ihtiyacının önümüzdeki dönemde belirleyici olacağını söylüyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "İstanbul",
    date: "22 Haziran 2026",
    readTime: "5 dk okuma",
    image:
      "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Şirketler, büyüme planlarında yapay zeka ve veri yetkinliklerini merkeze alıyor.",
    imageCredit: "Fotoğraf: The Guardian",
    source: { name: "The Guardian", url: "https://www.theguardian.com" },
    body: [
      "Teknoloji sektöründeki şirketler, yeni bir yatırım ve istihdam dalgasının eşiğinde olduklarını açıkladı. Büyüme planlarının merkezinde, yapay zeka ve veri analitiği alanlarındaki nitelikli iş gücü ihtiyacı yer alıyor.",
      "Sektör temsilcileri, yatırımların yalnızca yeni ürünlere değil; aynı zamanda mevcut çalışanların yeniden becerilendirilmesine (reskilling) ayrılacağını vurguluyor.",
      "İnsan kaynakları uzmanları, önümüzdeki dönemde rekabetin ürün kadar yetenek üzerinden de yaşanacağını; şirketlerin esnek çalışma modelleriyle nitelikli profilleri çekmeye çalışacağını belirtiyor.",
    ],
  },
  {
    id: "roman-odul",
    category: "Edebiyat",
    kicker: "Ödüller",
    title: "Yılın Roman Ödülü Sahibini Buldu: Jüriden 'Sessiz Ama Sarsıcı' Değerlendirmesi",
    dek: "Ödüllü eser, hafıza ve aidiyet temalarını ince bir dille işlediği gerekçesiyle öne çıktı.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    desk: "Londra",
    date: "22 Haziran 2026",
    readTime: "4 dk okuma",
    image:
      "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Jüri, eserin gösterişten uzak ama derin bir anlatı kurduğunu belirtti.",
    imageCredit: "Fotoğraf: The Guardian",
    source: { name: "The Guardian", url: "https://www.theguardian.com" },
    body: [
      "Yılın en prestijli roman ödüllerinden biri, hafıza ve aidiyet temalarını işleyen bir eserin oldu. Jüri, kitabın “sessiz ama sarsıcı” anlatımını ve dilindeki incelikli ekonomiyi öne çıkardı.",
      "Değerlendirmede, eserin büyük olaylardan çok gündelik ayrıntıların içinde derinleşen bir kurgu kurduğu vurgulandı. Ödülün, yazarın daha geniş bir okur kitlesine ulaşmasına katkı sağlaması bekleniyor.",
      "Edebiyat çevreleri, kararı çağdaş romanın yönüne dair bir işaret olarak yorumladı: Gösterişli değil, derinlikli anlatıya yöneliş.",
    ],
  },
  {
    id: "uyku-saglik",
    category: "Yaşam Tarzı",
    kicker: "Sağlıklı Yaşam",
    title: "Uzmanlardan Dijital Detoks Önerisi: Uyku Kalitesi Ekranla Düşüyor",
    dek: "Araştırmalar, yatmadan önceki ekran süresinin uyku düzenini bozduğuna dikkat çekiyor.",
    originalTitle:
      "Bunu yapan PİŞMAN OLMUYOR! Uzmanların gizlediği o sır ortaya çıktı, herkes şaşkın...",
    author: "Yeniden Yazım: Singularity AI Bot",
    rewritten: true,
    desk: "İstanbul",
    date: "21 Haziran 2026",
    readTime: "3 dk okuma",
    image:
      "https://images.unsplash.com/photo-1511295742362-92c96b1cf484?auto=format&fit=crop&w=1200&q=80",
    imageCaption:
      "Uzmanlar, yatmadan bir saat önce ekranları bırakmanın uyku kalitesini artırdığını belirtiyor.",
    imageCredit: "Fotoğraf: Hürriyet",
    source: { name: "Hürriyet", url: "https://www.hurriyet.com.tr" },
    body: [
      "Uyku sağlığı üzerine çalışan uzmanlar, yatmadan önceki ekran kullanımının uyku kalitesini olumsuz etkilediğine dikkat çekiyor. Mavi ışığa maruz kalmanın, vücudun doğal uyku ritmini geciktirebildiği belirtiliyor.",
      "Uzmanlar, akşam saatlerinde ekran süresini azaltmayı, yatmadan önce kısa bir “dijital detoks” uygulamayı ve uyku ortamını karanlık tutmayı öneriyor.",
      "Küçük alışkanlık değişikliklerinin bile zamanla uyku düzenine olumlu yansıyabileceği vurgulanıyor.",
    ],
  },
  {
    id: "derbi-sonucu",
    category: "Spor",
    kicker: "Süper Lig",
    title: "Nefes Kesen Derbide Kazanan Son Dakikada Belli Oldu",
    dek: "Karşılıklı gollerin yaşandığı mücadele, uzatma dakikalarındaki golle sonuçlandı.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Süper Lig — Spor masası derlemesi.",
    imageCredit: "Fotoğraf: BBC Sport",
    source: { name: "BBC Sport", url: "#" },
    body: [
      "İki ezeli rakip arasındaki derbi, sezonun en çok gol izlenen maçlarından biri oldu. Karşılaşma, uzatma dakikalarında bulunan golle sonuçlandı.",
      "Teknik direktörler, maç sonu açıklamalarında oyuncularının mücadele gücünü öne çıkardı. İki takım da pozisyon üretmekte zorlanmadı.",
      "Sonuç, şampiyonluk yarışındaki dengeleri yeniden kurdu; gözler bir sonraki haftanın kritik maçlarına çevrildi.",
    ],
  },
  {
    id: "sampiyonlar-ligi",
    category: "Spor",
    kicker: "Şampiyonlar Ligi",
    title: "Avrupa Arenasında Türk Takımına Zorlu Kura",
    dek: "Gruplardaki rakipler belli oldu; ilk maç deplasmanda oynanacak.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Şampiyonlar Ligi — Spor masası derlemesi.",
    imageCredit: "Fotoğraf: ESPN",
    source: { name: "ESPN", url: "#" },
    body: [
      "Şampiyonlar Ligi grup kuraları çekildi ve temsilcimiz zorlu bir gruba düştü. İlk maç deplasmanda oynanacak.",
      "Kulüp yönetimi, kura sonrası yaptığı açıklamada kadronun derinliğine güvendiklerini belirtti.",
      "Taraftarlar, gruptan çıkış için iç saha maçlarının belirleyici olacağı görüşünde.",
    ],
  },
  {
    id: "transfer-rekoru",
    category: "Spor",
    kicker: "Transfer",
    title: "Yaz Transfer Döneminde Rekor Bonservis Konuşuluyor",
    dek: "Kulüpler arası görüşmelerin sürdüğü, anlaşmanın hafta sonuna kadar tamamlanabileceği belirtiliyor.",
    author: "Yeniden Yazım: Singularity AI Bot",
    rewritten: true,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Transfer — Spor masası derlemesi.",
    imageCredit: "Fotoğraf: Fanatik",
    source: { name: "Fanatik", url: "#" },
    body: [
      "Yaz transfer döneminin en çok konuşulan ismi için kulüpler arası görüşmeler sürüyor. Bonservis bedelinin rekor düzeyde olabileceği belirtiliyor.",
      "Menajerlik kaynakları, oyuncunun kararını önümüzdeki günlerde vereceğini aktardı.",
      "Spor ekonomistleri, artan bonservis bedellerinin lig gelirleriyle orantılı büyümediği uyarısında bulunuyor.",
    ],
  },
  {
    id: "secim-sonuc",
    category: "Dünya",
    kicker: "Seçimler",
    title: "Avrupa'da Sandık: Merkez Partiler Oylarını Korudu",
    dek: "Yüksek katılımın gözlendiği seçimde koalisyon görüşmelerinin uzaması bekleniyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Seçimler — Dünya masası derlemesi.",
    imageCredit: "Fotoğraf: Reuters",
    source: { name: "Reuters", url: "#" },
    body: [
      "Avrupa'daki genel seçimde merkez partiler oylarını büyük ölçüde korudu. Yüksek katılım dikkat çekti.",
      "Sonuçların ardından koalisyon görüşmelerinin uzun sürebileceği değerlendiriliyor.",
      "Analistler, sonucun ekonomik istikrar mesajı olarak okunabileceğini belirtiyor.",
    ],
  },
  {
    id: "kur-altin",
    category: "Ekonomi",
    kicker: "Piyasalar",
    title: "Altın Yeni Zirvesini Test Ederken Kur Yatay Seyrediyor",
    dek: "Güvenli liman talebi sürerken yatırımcılar merkez bankası adımlarını bekliyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Piyasalar — Ekonomi masası derlemesi.",
    imageCredit: "Fotoğraf: Bloomberg",
    source: { name: "Bloomberg", url: "#" },
    body: [
      "Altın fiyatları, güvenli liman talebinin sürmesiyle yeni zirvesini test ediyor. Döviz kurlarında ise yatay bir seyir gözleniyor.",
      "Analistler, jeopolitik risklerin değerli metale ilgiyi canlı tuttuğunu belirtiyor.",
      "Piyasa katılımcıları, asıl yönün merkez bankalarının faiz mesajıyla belirleneceği görüşünde.",
    ],
  },
  {
    id: "yapay-zeka-asistan",
    category: "Teknoloji",
    kicker: "Yapay Zeka",
    title: "Yeni Nesil Yapay Zeka Asistanları Ofis Yazılımlarına Giriyor",
    dek: "Üreticiler, verimlilik vaadiyle gelen araçların mahremiyet sorularını da beraberinde getirdiğini kabul ediyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Yapay Zeka — Teknoloji masası derlemesi.",
    imageCredit: "Fotoğraf: The Guardian",
    source: { name: "The Guardian", url: "#" },
    body: [
      "Ofis yazılımlarına entegre edilen yeni nesil yapay zeka asistanları, belge yazımından veri analizine kadar pek çok görevi üstleniyor.",
      "Üreticiler, verimlilik artışının yanında veri mahremiyeti sorularının da gündeme geldiğini kabul ediyor.",
      "Uzmanlar, kurumların bu araçları benimserken net veri politikaları oluşturması gerektiğini vurguluyor.",
    ],
  },
  {
    id: "egitim-reform",
    category: "Gündem",
    kicker: "Eğitim",
    title: "Üniversite Sınavı Takviminde Güncelleme Açıklandı",
    dek: "Adayların hazırlık sürecini etkileyecek değişikliklerin kademeli uygulanacağı bildirildi.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Eğitim — Gündem masası derlemesi.",
    imageCredit: "Fotoğraf: NTV",
    source: { name: "NTV", url: "#" },
    body: [
      "Üniversiteye giriş sınavının takvimine ilişkin güncelleme açıklandı. Değişikliklerin kademeli uygulanacağı belirtildi.",
      "Eğitimciler, adayların hazırlık planını etkileyecek düzenlemelerin erken duyurulmasını olumlu buldu.",
      "Yetkililer, sürecin şeffaf yürütüleceğini ve ayrıntıların kılavuzda yer alacağını bildirdi.",
    ],
  },
  {
    id: "saglikli-mutfak",
    category: "Yaşam Tarzı",
    kicker: "Beslenme",
    title: "Akdeniz Mutfağı Yeniden Gözde: Uzmanlardan Mevsimsel Öneriler",
    dek: "Diyetisyenler, işlenmiş gıdaların azaltılmasının uzun vadeli faydalarına dikkat çekiyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Beslenme — Yaşam Tarzı masası derlemesi.",
    imageCredit: "Fotoğraf: Metro UK",
    source: { name: "Metro UK", url: "#" },
    body: [
      "Akdeniz mutfağı, dengeli içeriği ve mevsimsel ürünlere dayanması nedeniyle yeniden gündemde. Diyetisyenler sade tarifleri öne çıkarıyor.",
      "Uzmanlar, işlenmiş gıdaların azaltılmasının uzun vadeli sağlık faydaları olduğunu vurguluyor.",
      "Mevsimsel ve yerel ürünlerin hem sağlık hem sürdürülebilirlik açısından tercih edilmesi öneriliyor.",
    ],
  },
  {
    id: "sergi-istanbul",
    category: "Kültür Sanat",
    kicker: "Sergi",
    title: "Modern Sanat Müzesinde Büyük Retrospektif Kapılarını Açtı",
    dek: "Sergi, sanatçının kırk yıllık üretimini ilk kez bir arada izleyiciyle buluşturuyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1507924538820-ede94a04019d?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Sergi — Kültür Sanat masası derlemesi.",
    imageCredit: "Fotoğraf: ARTnews",
    source: { name: "ARTnews", url: "#" },
    body: [
      "Modern sanat müzesinde açılan retrospektif, sanatçının kırk yıla yayılan üretimini bir arada sunuyor. Sergi yoğun ilgi görüyor.",
      "Küratörler, seçkinin sanatçının az bilinen dönemlerine de ışık tuttuğunu belirtiyor.",
      "Sergiye eşlik eden söyleşi ve atölye programının önümüzdeki aylarda süreceği açıklandı.",
    ],
  },
  {
    id: "girisim-yatirim",
    category: "İş",
    kicker: "Girişim",
    title: "Yerli Girişime Büyük Yatırım: Hedef Avrupa Pazarı",
    dek: "Yatırımın, şirketin mühendislik kadrosunu genişletmesi ve uluslararasılaşması için kullanılacağı belirtiliyor.",
    author: "Çeviri: Singularity AI Bot",
    rewritten: false,
    date: "21 Haziran 2026",
    readTime: "4 dk okuma",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    imageCaption: "Girişim — İş masası derlemesi.",
    imageCredit: "Fotoğraf: Axios",
    source: { name: "Axios", url: "#" },
    body: [
      "Yerli bir teknoloji girişimi, büyüme turunda önemli bir yatırım aldı. Şirketin hedefinde Avrupa pazarı var.",
      "Kurucular, kaynağın mühendislik kadrosunu genişletmek ve ürünü uluslararasılaştırmak için kullanılacağını açıkladı.",
      "Yatırımcılar, bölgedeki girişim ekosisteminin olgunlaştığına dikkat çekiyor.",
    ],
  },
];

/* Köşe yazarı demosu (backend yoksa). GERÇEK yazarlar — uydurma yazı içermez;
   yazıları backend'den gelir, çevrimdışıyken yazar sayfasına link verilir. */
export const MOCK_COLUMNISTS = [
  { slug: "marina-hyde", name: "Marina Hyde", title: "The Guardian · Köşe Yazarı", avatar: null, page: "https://www.theguardian.com/profile/marinahyde", columns: [] },
  { slug: "george-monbiot", name: "George Monbiot", title: "The Guardian · Çevre & Politika", avatar: null, page: "https://www.theguardian.com/profile/georgemonbiot", columns: [] },
  { slug: "owen-jones", name: "Owen Jones", title: "The Guardian · Politika", avatar: null, page: "https://www.theguardian.com/profile/owen-jones", columns: [] },
  { slug: "polly-toynbee", name: "Polly Toynbee", title: "The Guardian · Politika", avatar: null, page: "https://www.theguardian.com/profile/pollytoynbee", columns: [] },
  { slug: "jonathan-freedland", name: "Jonathan Freedland", title: "The Guardian · Köşe Yazarı", avatar: null, page: "https://www.theguardian.com/profile/jonathanfreedland", columns: [] },
  { slug: "ahmet-hakan", name: "Ahmet Hakan", title: "Hürriyet · Köşe Yazarı", avatar: null, page: "https://www.hurriyet.com.tr/yazarlar/ahmet-hakan/", columns: [] },
  { slug: "abdulkadir-selvi", name: "Abdulkadir Selvi", title: "Hürriyet · Köşe Yazarı", avatar: null, page: "https://www.hurriyet.com.tr/yazarlar/abdulkadir-selvi/", columns: [] },
  { slug: "deniz-zeyrek", name: "Deniz Zeyrek", title: "Sözcü · Köşe Yazarı", avatar: null, page: "https://www.sozcu.com.tr/yazarlari/deniz-zeyrek/", columns: [] },
  { slug: "mehmet-y-yilmaz", name: "Mehmet Y. Yılmaz", title: "Köşe Yazarı", avatar: null, page: "", columns: [] },
];
